### PR TITLE
Added favicon and Fixed Chrome Installation

### PR DESCRIPTION
**Pull request by tenzyu**
# このロゴセンスあるね😎

### CODE REVIEW

**Comment by tenzyu** [comment]
# This branch has no conflicts with the base branch!
## It's so lovely good so fucking good that I've set a fucking icon as favicon and apple-touch-icon also I solved minifest.json problems, and and and Supported offline launch wow wow
# SO YOU MUST MARGE IT NOW, MATE
### btw, Grammarly: Your fucking English is so waste and holy shit
### Me: ai kyan notto supi-ku ingurisshu
#### I mean iikanjini iikanji sitekure
頼むわ😎

**Comment by tenzyu** [comment]
なんか、開発環境だったらオフラインでも動いたのに、netlify側からだったらできないんだが
修正するわ

**Comment by tenzyu** [comment]
Chromeの開発ツールのオフラインモードでは動作するが、実際のオフラインモードでは動作しないことを確認できた。
根本からの修正なので、待たずに現時点のコードをそのままマージしてくれて大丈夫。

**Comment by tenzyu** [comment]
I've given up on offline support.

**Comment by tenzyu** [comment]
> # This branch has no conflicts with the base branch!
> ## It's so lovely good so fucking good that I've set a fucking icon as favicon and apple-touch-icon also I solved minifest.json problems, ~~and and and Supported offline launch wow wow~~
> # SO YOU MUST MARGE IT NOW, MATE
> ### btw, Grammarly: Your fucking English is so waste and holy shit
> ### Me: ai kyan notto supi-ku ingurisshu
> #### I mean iikanjini iikanji sitekure
> 頼むわ😎

**Comment by hiraginoyuki** [comment]
you fucking loud lmao
ok ill marge the shit soon

**Comment by hiraginoyuki** [comment]
great

**Review by hiraginoyuki — APPROVED** [review]

**Review by hiraginoyuki — APPROVED** [review]

**Review by hiraginoyuki — APPROVED** [review]

**Review by hiraginoyuki — APPROVED** [review]

**Comment by hiraginoyuki** [comment]
lol

**Pull request merged**
